### ISSUE TITLE
Error with django-simple-captcha version when installing with pip

### ISSUE THREAD

**Issue by synw** [dlancer/django-crispy-contact-form#4]
Downloading/unpacking django-simple-captcha>=0.4.6 (from django-crispy-contact-form)
  Could not find a version that satisfies the requirement django-simple-captcha>=0.4.6 (from django-crispy-contact-form) (from versions: )
No distributions matching the version for django-simple-captcha>=0.4.6 (from django-crispy-contact-form)

**Comment by synw** [comment]
pip install django-simple-captcha
--> gives django-simple-captcha==0.4.5

**Comment by dlancer** [comment]
I don't have any problems with 0.4.6
https://pypi.python.org/pypi/django-simple-captcha/0.4.6

**Comment by synw** [comment]
That was it: outdated pip, sorry
